// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace X4QU.Sample {
    using System;
    using Xamarin.QuickUI;
    
    
    public partial class CustomPage {
        
        private StackLayout Stack;
        
        private Label Label0;
        
        private Label Label1;
        
        private void InitializeComponent() {
            this.LoadFromXaml(typeof(CustomPage));
            Stack = this.FindById <StackLayout>("Stack");
            Label0 = this.FindById <Label>("Label0");
            Label1 = this.FindById <Label>("Label1");
        }
    }
}
